// <auto-generated />
using System;
using IQC_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IQC_API.Migrations
{
    [DbContext(typeof(IQC_API_PG_Context))]
    [Migration("20250916002614_AddCheckItems")]
    partial class AddCheckItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IQC_API.Models.InspectionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualCheckTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Approver")
                        .HasColumnType("text");

                    b.Property<string>("CheckItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckLot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckMonitor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassOne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassTwo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContinuedEligibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignNoticeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DimenstionsMaxSamplingCheckQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstAppearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourMNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IQCCheckDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LotJudge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OccuredEngineer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutgoingInspectionReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProficienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedCheckLot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingCheckDefectiveQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingCheckQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingRejectQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondAppearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StockInCollectDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreeCDataConfirm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalLotQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InspectionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
