// <auto-generated />
using System;
using IQC_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IQC_API.Migrations
{
    [DbContext(typeof(IQC_API_PG_Context))]
    [Migration("20260205090857_MachineLotRequestOptionals")]
    partial class MachineLotRequestOptionals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IQC_API.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("FontColor")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("MesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IQC_API.Models.InspectionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualCheckTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllowQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Approver")
                        .HasColumnType("text");

                    b.Property<string>("CheckLot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckMonitor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassOne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassTwo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContinuedEligibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignNoticeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DimensionCheckItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DimenstionsMaxSamplingCheckQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstAppearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FourMNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IQCCheckDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LotJudge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OccuredEngineer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutgoingInspectionReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProficienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedCheckLot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingCheckDefectiveQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingCheckQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SamplingRejectQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondAppearance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StockInCollectDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreeCDataConfirm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalLotQty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisualCheckItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InspectionDetails");
                });

            modelBuilder.Entity("IQC_API.Models.MachineLotRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckLot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DCIOtherNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseNo")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseReasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WhatForId")
                        .HasColumnType("integer");

                    b.Property<bool>("YellowCard")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseReasonId");

                    b.HasIndex("WhatForId");

                    b.ToTable("MachineLotRequest");
                });

            modelBuilder.Entity("IQC_API.Models.PartsInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("CommonGroup")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriticalComponentSafety")
                        .HasColumnType("text");

                    b.Property<string>("DimensionTT")
                        .HasColumnType("text");

                    b.Property<string>("EOL")
                        .HasColumnType("text");

                    b.Property<string>("EOLDate")
                        .HasColumnType("text");

                    b.Property<string>("FutureInspectionStatus")
                        .HasColumnType("text");

                    b.Property<string>("InspectionStatus")
                        .HasColumnType("text");

                    b.Property<string>("JIT")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Markings")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("ModelCategory")
                        .HasColumnType("text");

                    b.Property<string>("N1N2")
                        .HasColumnType("text");

                    b.Property<string>("N_Z")
                        .HasColumnType("text");

                    b.Property<string>("OverseasManufacturer")
                        .HasColumnType("text");

                    b.Property<string>("PSMark")
                        .HasColumnType("text");

                    b.Property<string>("PartCode")
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .HasColumnType("text");

                    b.Property<string>("Plant")
                        .HasColumnType("text");

                    b.Property<string>("QMLotCategory")
                        .HasColumnType("text");

                    b.Property<string>("QM_Lot_Category")
                        .HasColumnType("text");

                    b.Property<string>("QualityLevel")
                        .HasColumnType("text");

                    b.Property<string>("Reference_STS_Checking")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SAPMasterRegistration")
                        .HasColumnType("text");

                    b.Property<string>("SFCategory")
                        .HasColumnType("text");

                    b.Property<string>("STS_N1")
                        .HasColumnType("text");

                    b.Property<string>("STS_Normal_N1")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Sloc")
                        .HasColumnType("text");

                    b.Property<string>("StandardTaktTime")
                        .HasColumnType("text");

                    b.Property<string>("SupplierData")
                        .HasColumnType("text");

                    b.Property<string>("SupplierName")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VendorCode")
                        .HasColumnType("text");

                    b.Property<string>("VisualDimension")
                        .HasColumnType("text");

                    b.Property<string>("VisualTT")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartsInformation");
                });

            modelBuilder.Entity("IQC_API.Models.ReleaseReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReleaseReasonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReleaseReasonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReleaseReason");
                });

            modelBuilder.Entity("IQC_API.Models.SystemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("System");
                });

            modelBuilder.Entity("IQC_API.Models.WhatFor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WhatForCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatForDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatForName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WhatFor");
                });

            modelBuilder.Entity("IQC_API.Models.MachineLotRequest", b =>
                {
                    b.HasOne("IQC_API.Models.ReleaseReason", "ReleaseReason")
                        .WithMany("MachineLotRequests")
                        .HasForeignKey("ReleaseReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQC_API.Models.WhatFor", "WhatFor")
                        .WithMany("MachineLotRequests")
                        .HasForeignKey("WhatForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReleaseReason");

                    b.Navigation("WhatFor");
                });

            modelBuilder.Entity("IQC_API.Models.ReleaseReason", b =>
                {
                    b.Navigation("MachineLotRequests");
                });

            modelBuilder.Entity("IQC_API.Models.WhatFor", b =>
                {
                    b.Navigation("MachineLotRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
